#+TITLE: My personal library of scientific works
#+AUTHOR: Luis Paulo M. Lima

* Introduction
This file contains entries for almost all of the papers I have
gathered for my research at CNU.  Each entry should be like this:

#+begin_src
  ,** Title of the paper
   This heading should be empty but should be tagged with the
   corresponding citation key found in library.bib.

  ,*** Authors
   The ``Authors'' should contain only a simple list with the name of
   the authors.

  ,*** Keywords
   The ``Keywords'' heading should be blank and have tags that match the
   keywords given in the paper, if any. Personal tags can be added too.

  ,*** Links
   At least one link should be given: to either a file or a internet
   reference where the paper can be found.  If the reference is online,
   a DOI is prefered.

  ,*** Summary
   A summary written by myself, sumarizing the contents of the paper.
   It should not be a copy of the abstract, by my own understanding of
   the what it contains.  It could also be simply a list with the main
   topics contained in it.  Also, a list of personal tags can be added
   to this heading.
#+end_src

Each entry should also be placed under an appropriate top level
heading:
 - Books and theses
 - Conference papers
 - Journal papers
 - Others references

* Books and theses
  Empty.

* Conference papers

** High-speed, non-contact, baseline-free imaging of hidden defects using scanning laser measurements of steady-state ultrasonic vibration :flynn2013:
*** Authors
    - E. B. Flynn
    - G. S. Jarmer
*** Keywords                                    :ldv:wavenumber:steady_state:
*** Links
    - [[https://www.dpi-proceedings.com/index.php/shm2013/article/view/22912][Conference website]]
    - [[https://www.researchgate.net/publication/259102704_High-Speed_Non-Contact_Baseline-Free_Imaging_of_Hiddden_Defects_Using_Scanning_Laser_Measurements_of_Steady-State_Ultrasonic_Vibration][ResearchGate]]
    - [[./flynn2013.pdf]]
*** Summary
    The most basic text for understanding LDV scanning.  It sets the
    foundation for the techniques used at ASDL in a very simple way.
    It lacks, however, a deeper explanation on how the /wavenumber
    filter bank/ and the /monogenic signal/ work, and assumes that
    this is common knowledge for anyone reading the paper (which, in
    fact, should be).

* Journal papers

** 2D-wavelet wavenumber filtering for structural damage detection using full steady-state wavefield laser scanning :junyoung2020:
*** Keywords :steady_state_wavefield:shm:nondestructive_evaluation:damage_detection:wavelet:laser:ldv:
*** Links
    - [[https://doi.org/10.1016/j.ndteint.2020.102343][Journal]]
    - [[./junyoung2020.pdf]]
*** TODO Summary
    TBD.

* Other references
  Empty.
