:PROPERTIES:
:ID: library
:END:
#+TITLE: My personal library of scientific works
#+AUTHOR: Luis Paulo M. Lima
#+PROPERTY: header-args :tangle yes

* Introduction
This file contains entries for almost all of the papers I have gathered for my research at CNU, and each entry should also be placed under an appropriate top level
heading:
- Books and theses
- Conference papers
- Journal papers
- Others references
The entries should be a level-2 heading placed under the top level heading listed above and should also be a node for Org-Roam, therefore they need a Org mode property drawer with an =ID= field.

Each entry should have the following format:
#+begin_src org :tangle no
  ,** <title> <keywords>
  :PROPERTIES:
  :ID: <entry id>
  :CATEGORY: <entry category>
  :END:
  - Added: <timestamp>
  - Year: <year>
  - Author: <author|list of authors>

  ,*** Resources:
  - <local file|remote resource>

  ,*** Citation
  ,#+begin_src bibtex
    @<type>{<entry id>,
        <bib-entry>}
  ,#+end_src

  [<rest>]
#+end_src

The =title= should match the actual title of the work, and =keywords= are Org tags corresponding to list of keywords listed in the work.
Additional tags not originally contained in the work could be added to improve classification and in-file search.
In the properties drawer of the entry, there should be =ID= field whose value is =entry id=.
The =entry id= should be of the format =<name><year>[-<N>]=, where =name= is the last name of the first author, and =year= is the four digit year of publication.
If there is more than one work for the same author in the same year, an additional digit =N= preceded by a dash should be added to the =id=.
The =CATEGORY= field is redundant given that each entry is already under a top-level heading describing the type of entry and won't be present in an HTML view of this library.
However, it is useful for searching this file in Emacs, since =org-agenda= which is on what =library-search= is based, uses these properties for grouping and displaying results.
The value for =entry category= can be anything that helps describe the type of work, like "Book", "Journal" or "Conference".
Next, the actual content of the entries are described.

Under the top-most heading for the entry there should be a list of the authors, the year of publication, and date the entry was added:
- the =timestamp= should be added using =org-time-stamp= in the date the entry was added to the library.
- the year should have the same format as =entry id=, i.e. four digits.
- if there is a single author, they should be named in a single line.
- if there are more than one author, they should be named in a list under ``Author''.

The following subheadings should also be contained in the entry:

- Resources:

  Hyper-links to the references should be added here, preferably two, but at least one:
  - a =local file= is a external file in current machine.
  - a =remote resource= is a URL on the Internet, preferably a Document Object Identifier (DOI).

- Citation

  A BibTeX entry placed inside a Org =src-block= whose language should be =bibtex=.
  These blocks will be tangled by Org-Babel into a single [[file:./library.bib][.bib file]].

  The entry's key should be =id=, the same value used in the =ID= field in the properties drawer for Org-Roam, and =bib-entry= are the field-value pairs composing the entry.
  The =type= value is the type of the entry and should correspond to the top level heading in which the entry is placed:
  - =book=, =phdthesis= or =masterthesis= for ``Books and theses'',
  - =inproceedings= for ``Conference papers'',
  - =article= for ``Journal papers'',
  - any other appropriate type for ``Other references''.

After the Resources and Citation sub-headings, any type of notes can be added in the optional =rest=, which should be in level-3 sub-headings.
Ideally I will add a summary my impressions of the work, which is useful to state the reason why I added the work to the library.
It is also common that I add a =TODO= state the to summary when I think that I should write it but have not done it yet.

This is the end of the Introduction and the actual library follows from here.

* Books and theses

** A wavelet tour of signal processing: the sparse way :wavelet:basic_literature:
:PROPERTIES:
:ID: mallat2009
:CATEGORY: Book
:END:
- Added: <2022-05-02 Mon>
- Year: 2009
- Author: Stéphane Mallat

*** Resources:
- [[file:./resources/mallat2009.pdf][File]]

*** Citation
#+begin_src bibtex
  @book{mallet2008,
      author = 	 {Stéphane Mallat},
      title = 	 {A wavelet tour of signal processing},
      publisher = 	 {Academic Press},
      year = 	 2009,
      address = 	 {Burlington},
      edition = 	 {3rd}
  }
#+end_src

*** Summary
The first four chapters of this book are really impressive.  It
reviews the basic theory of signal processing up to a point where the
reader, if they are experienced enough with Fourier Analysis, will
turn out to have a very good understanding of the of the concept of
the wavelet transformation.

** Two-dimensional signal and image processing           :signal_processing:
:PROPERTIES:
:ID: jaeslim1990
:CATEGORY: Book
:END:
- Added: <2021-11-05 Fri>
- Year: 1990
- Author: Jae S. Lim

*** Resources:
- [[file:./resources/jaeslim1990.djvu][File]]

*** Citation
#+begin_src bibtex
  @book{jaeslim1990,
      author = 	 {Jae S Lim},
      title = 	 {Two-dimensional signal and image processing},
      publisher =  {Prentice Hall},
      year = 	 1990,
      address = 	 {New Jersey}}
#+end_src

*** TODO Summary
TBD.

** Wave motion in elastic solids         :wave_propagation:basic_literature:
:PROPERTIES:
:ID: graff1975
:CATEGORY: Book
:END:
- Added: <2021-10-27 Wed>
- Year: 1975
- Author: Karl F. Graff

*** Resources:
- [[file:./resources/graff1975.pdf][File]]

*** Citation
#+begin_src bibtex
  @book{graff1975,
    author = 	 {Karl F. Graff},
    title = 	 {Wave motion in elastic solids},
    publisher = 	 {Dover Publications},
    year = 	 1975,
    address = 	 {New York}}
#+end_src

*** Summary
This was my entry point to the theory of wave propagation.  It
starts from 1D case for a string, then a rod, then beam, and give
exhaustive examples and explanations from every aspect and
question in each chapter.  It is an incredible resource for
learning but, at the same time, the math used here is very heavy.
However, by overlooking the hard points, it should help anyone
understand this topic.  I highly recommend it, and I also
recommend not to rush through it.  Take your time, it is not easy,
but it is very rewarding.

** Ten Lectures of Wavelets                      :wavelet:signal_processing:
:PROPERTIES:
:ID: daubechies1992
:CATEGORY: Book
:END:
- Added: <2022-01-29 Sat>
- Year: 1992
- Author: Ingrid Daubechies

*** Resources:
- [[file:./resources/daubechies1992.pdf][File]]

*** Citation
#+begin_src bibtex
@book{daubachies1992,
  author = 	 {Ingrid Daubachies},
  title = 	 {Ten lectures on wavelets},
  publisher = 	 {SIAM},
  year = 	         1992,
  address = 	 {Pennsylvania}}
#+end_src

*** Summary
TBD.

** Fundamentals of Signal Processing for Sound and Vibration Engineers :signal_processing:
:PROPERTIES:
:ID: shin2008
:CATEGORY: Book
:END:
- Added: <2022-08-18 Thu>
- Year: 2008
- Author:
  - Kihong Shin
  - Joseph Hammond

*** Resources
- [[file:./resources/shin2008.pdf][File]]


*** Citation
#+begin_src bibtex
  @book{shin2008,
    author =    {Kihong Shin and Joseph Hammond},
    title =        {Fundamentals of Signal Processing for Sound and Vibration Engineers},
    publisher =    {Wiley},
    year =         2008,
    address =   {Sussex}}
#+end_src

*** Summary
So far, one of the best books for needs of understanding Signal Processing, specifically because of the second part on Random Processes, which introduces Correlation.

** Piezoelectric-based in-situ damage detection of composite materials for Structural Health Monitoring Systems :lamb_waves:basic_literature:
:PROPERTIES:
:ID: kessler2002
:CATEGORY: Thesis
:END:
- Added: <2022-09-28 Wed>
- Year: 2002
- Author: Seth Stovack Kessler

*** Resources
- [[http://dspace.mit.edu/handle/1721.1/16836][MIT Online Library]]
- [[file:./resources/kessler2002.pdf][File]]


*** Citation
#+begin_src bibtex
@phdthesis{kessler2002,
  author =       {Seth Stovack Kessler},
  title =        {Piezoelectric-based in-situ damage detection of composite materials for Structural Health Monitoring Systems},
  school =       {Massachusetts Institute of Technology},
  year =         2002}
#+end_src

*** Summary
Its chapter on Lamb wave gives a very extensive and deep review on the literature which is very useful for finding old and original papers on the subject.
On the other hand, the results of the thesis themselves do not show anything new, and are (probably) obsolete.

* Conference papers

** Embedded multi-tone ultrasonic excitation and continuous-scanning laser Doppler vibrometry for rapid and remote imaging of structural defects :laser:guided_wave:
:PROPERTIES:
:CATEGORY: Conference
:ID: flynn2014
:END:
- Added: <2022-02-21 Mon>
- Year: 2014
- Author: Eric B. Flynn

*** Resources:
- [[https://hal.inria.fr/hal-01021054/][Conference website]]
- [[file:./resources/flynn2014.pdf][File]]

*** Citation
#+begin_src bibtex
  @inproceedings{flynn2014,
    title = {Embedded Multi-Tone Ultrasonic Excitation and Continuous-Scanning Laser Doppler Vibrometry for Rapid and Remote Imaging of Structural Defects},
    author = {Eric B. Flynn},
    url = {https://hal.inria.fr/hal-01021054},
    booktitle = {{EWSHM - 7th European Workshop on Structural Health Monitoring}},
    address = {Nantes, France},
    organization = {{IFFSTTAR, Inria, Universit{\'e} de Nantes}},
    editor = {Le Cam and Vincent and Mevel and Laurent and Schoefs and Franck},
    year = {2014},
    month = Jul,
    pdf = {https://hal.inria.fr/hal-01021054/file/0376.pdf},
  }
#+end_src

*** TODO Summary
TBD.

** Exploring the performance limits of full-field acoustic wavenumber spectroscopy techniques for damage detection through numerical simulation :fem:aws:
:PROPERTIES:
:ID: odowd2016
:CATEGORY: Conference
:END:
- Added: <2021-11-22 Mon>
- Year: 2016
- Authros:
  - Niall M. O'Dowd
  - Dae-Hyun Han
  - Lae-Hyong Kang
  - Eric B. Flynn

*** Resources
- [[https://www.ndt.net/search/docs.php3?id=20089][Conference website]]
- [[file:./resources/odowd2016.pdf][File]]

*** Citation
#+begin_src bibtex
  @inproceedings{odowd2016,
    author = 	 {Niall M. O'Dowd and Dae-Hyun Han and Lae-Hyong Kang and Eric B. Flynn},
    title = 	 {Exploring the performance limits of full-field acoustic wavenumber spectroscopy techniques for damage detection through numerical simulation},
    year = 	 2016,
    volume = 	 1,
    booktitle =    {8th European Workshop on Structural Health Monitoring}}
#+end_src

*** Summary
Presents a comprehensive study on the robustness of AWS technique
using FEM.  It is not hard to read this paper, but it presents a great
amount of results.  It is also a valuable source of ideas to run tests
on future techniques based or similar to AWS.

** Three-dimensional acoustic wavenumber spectroscopy for structural health monitoring :aws:
:PROPERTIES:
:ID: fickenwirth2019
:CATEGORY: Conference
:END:
- Added: <2021-11-17 Wed>
- Year: 2019
- Authors:
  - Peter H. Fickenwirth
  - Matthew J. Adams
  - Eric B. Flynn

*** Resources
- [[http://doi.org/10.12783/shm2019/32196][Conference website]]
- [[file:./resources/fickenwirth2019.pdf][File]]

*** Citation
#+begin_src bibtex
  @inproceedings{fickenwirth2019,
    author = 	 {Peter H. Fickenwirth and Matthew J. Adams and Eric B. Flynn},
    title = 	 {Three-dimensional acoustic wavenumber spectroscopy for structural health monitoring },
    booktitle = {12th International Workshop on Structural Health Monitoring},
    year = 	 2019,
    volume = 	 1}
#+end_src

*** TODO Summary
TBD.

** High-speed, non-contact, baseline-free imaging of hidden defects using scanning laser measurements of steady-state ultrasonic vibration :ldv:wavenumber:steady_state:
:PROPERTIES:
:ID: flynn2013
:CATEGORY: Conference
:END:
- Added: <2021-10-21 Thu>
- Year: 2013
- Authors:
  - E. B. Flynn
  - G. S. Jarmer

*** Resources
- [[https://www.dpi-proceedings.com/index.php/shm2013/article/view/22912][Conference website]]
- [[https://www.researchgate.net/publication/259102704_High-Speed_Non-Contact_Baseline-Free_Imaging_of_Hiddden_Defects_Using_Scanning_Laser_Measurements_of_Steady-State_Ultrasonic_Vibration][ResearchGate]]
- [[file:./resources/flynn2013.pdf][File]]

*** Citation
#+begin_src bibtex
  @inproceedings{flynn2013,
    author = 	 {E. B. Flynn and G. S. Jarmer},
    title = 	 {High-Speed, Non-Contact, Baseline-Free Imaging of
                    Hiddden Defects Using Scanning Laser Measurements of
                    Steady-State Ultrasonic Vibration},
    booktitle =	 {9th International Workshop on Structural Health
                    Monitoring},
    year =	 {2013},
    volume =	 {1}}
#+end_src

*** Summary
The most basic text for understanding LDV scanning.  It sets the
foundation for the techniques used at ASDL in a very simple way.
It lacks, however, a deeper explanation on how the /wavenumber
filter bank/ and the /monogenic signal/ work, and assumes that
this is common knowledge for anyone reading the paper (which, in
fact, should be).

* Journal papers

** Identification of cracks in thin-walled structures by means of wavenumber filtering :lamb_waves:wavenumber:laser:
:PROPERTIES:
:ID: kudela2015
:CATEGORY: Journal
:END:
- Added: <2022-02-21 Mon>
- Year: 2015
- Authors:
  - Paweł Kudela
  - Maciej Radzieński
  - Wiesław Ostachowicz

*** Resources
- [[https://doi.org/10.1016/j.ymssp.2014.05.041][Journal]]
- [[file:./resources/kudela2015.pdf][File]]

*** Citation
#+begin_src bibtex
  @article{kudela2015,
    title = {Identification of cracks in thin-walled structures by means of wavenumber filtering},
    journal = {Mechanical Systems and Signal Processing},
    volume = {50-51},
    pages = {456-466},
    year = {2015},
    issn = {0888-3270},
    doi = {https://doi.org/10.1016/j.ymssp.2014.05.041},
    url = {https://www.sciencedirect.com/science/article/pii/S0888327014002179},
    author = {Paweł Kudela and Maciej Radzieński and Wiesław Ostachowicz},
    keywords = {Lamb waves, Wavefield, Crack identification, Wavenumber filtering, Laser vibrometry}
    }
#+end_src

*** TODO Summary
TBD.

** Structural imaging through local wavenumber estimation of guided waves :ndt:ldv:image_processing:ultrasonic:wavenumber:
:PROPERTIES:
:CATEGORY: Journal
:ID: flynn2013-2
:END:
- Added: <2021-11-23 Tue>
- Year: 2013
- Authors:
  - Eric B. Flynn
  - See Yenn Chong
  - Gregory J. Jarmer
  - Jung-Ryul Lee

*** Resources
- [[https://doi.org/10.1016/j.ndteint.2013.04.003][Journal]]
- [[file:./resources/flynn2013-2.pdf][File]]

*** Citation
#+begin_src bibtex
  @article{flynn2013-2,
    title = {Structural imaging through local wavenumber estimation of guided waves},
    journal = {NDT \& E International},
    volume = {59},
    pages = {1-10},
    year = {2013},
    issn = {0963-8695},
    doi = {https://doi.org/10.1016/j.ndteint.2013.04.003},
    url = {https://www.sciencedirect.com/science/article/pii/S0963869513000595},
    author = {Eric B. Flynn and See Yenn Chong and Gregory J. Jarmer and Jung-Ryul Lee},
    keywords = {Nondestructive testing, Ultrasonic guided waves, Laser-generated ultrasound, Image processing}}
#+end_src

*** TODO Summary
TBD.

** Finite element prediction of wave motion in structural waveguides :FEM:basic_literature:waveguide:
:PROPERTIES:
:CATEGORY: Journal
:ID: mace2005
:END:
- Added: <2021-11-12 Fri>
- Year: 2005
- Authors:
  - Brian R. Mace
  - Denis Duhamel
  - Michael J. Brennan
  - Lars Hinke

*** Resources
- [[https://doi.org/10.1121/1.1887126][Journal]]
- [[file:./resources/mace2005.pdf][File]]

*** Citation
#+begin_src bibtex
  @article{mace2005,
    author = {Brian R. Mace and Denis Duhamel and Michael J. Brennan and Lars Hinke},
    title = {Finite element prediction of wave motion in structural waveguides},
    journal = {The Journal of the Acoustical Society of America},
    volume = {117},
    number = {5},
    pages = {2835-2843},
    year = {2005},
    doi = {10.1121/1.1887126},
    URL = {https://doi.org/10.1121/1.1887126},
    eprint = {https://doi.org/10.1121/1.1887126}}
#+end_src

*** Summary
One of the most basic works on Finite Elements Method applied to
waveguides.  In contrast with other works, this one presents a simple
method that does not involve new types of elements, and depend only on
the regular stiffness, mass and damping matrices of the matrices used
in common FEM experiments.  Basic knowledge of FEM theory is the only
requirement to understand this paper.

** Frequency-wavenumber domain filtering for improved damage visualization :wavefield:wavenumber:filter:basic_literature:
:PROPERTIES:
:CATEGORY: Journal
:ID: ruzzene2007
:END:
- Added: <2021-10-27 Wed>
- Year:  2007
- Author: M Ruzzene

*** Resources
- [[https://doi.org/10.1063/1.2718150][Journal]]
- [[file:./resources/ruzzene2007.pdf][File]]

*** Citation
#+begin_src bibtex
  @article{ruzzene2007,
    author = {M. Ruzzene},
    title = {Frequency‐Wavenumber Domain Filtering for Improved Damage Visualization},
    journal = {AIP Conference Proceedings},
    volume = {894},
    number = {1},
    pages = {1556-1563},
    year = {2007},
    doi = {10.1063/1.2718150},
    URL = {https://aip.scitation.org/doi/abs/10.1063/1.2718150},
    eprint = {https://aip.scitation.org/doi/pdf/10.1063/1.2718150}}
#+end_src

*** Summary
Very short but very insightful paper presenting the concept of
filtering in the wavenumber-frequency domain. Although it leaves
out how to generate and how to apply the windows for filtering,
this paper should be considered basic literature for the work done
in ADSL.

** 2D-wavelet wavenumber filtering for structural damage detection using full steady-state wavefield laser scanning :steady_state_wavefield:shm:nondestructive_evaluation:damage_detection:wavelet:laser:ldv:
:PROPERTIES:
:ID: junyoung2020
:CATEGORY: Journal
:END:
- Added: <2021-10-22 Fri>
- Year: 2020
- Authors:
  - Jun Young Jeon
  - Duhwan Kim
  - Gyuhae Park
  - Eric Flynn
  - To Kang
  - Soonwoo Han

*** Resources
- [[https://doi.org/10.1016/j.ndteint.2020.102343][Journal]]
- [[file:./resources/junyoung2020.pdf][File]]

*** Citation
#+begin_src bibtex
  @article{junyoung2020,
    title = {2D-wavelet wavenumber filtering for structural damage detection using full steady-state wavefield laser scanning},
    journal = {NDT & E International},
    volume = {116},
    pages = {102343},
    year = {2020},
    issn = {0963-8695},
    doi = {https://doi.org/10.1016/j.ndteint.2020.102343},
    url = {https://www.sciencedirect.com/science/article/pii/S0963869520300384},
    author = {Jun Young Jeon and Duhwan Kim and Gyuhae Park and Eric Flynn and To Kang and Soonwoo Han},
    keywords = {Steady-state wavefield, Structural health monitoring, Nondestructive evaluation, Damage detection, 2D-wavelet filter, Laser scanning}}
#+end_src

*** TODO Summary
TBD.

** Experimental Confirmation of Lamb Waves at Megacycle Frequencies :wave_propagation:basic_literature:
:PROPERTIES:
:ID: worlton1961
:CATEGORY: Journal
:END:
- Added: <2022-09-28 Wed>
- Year: 1961
- Author: D. C. Worlton

*** Resources
- [[http://dx.doi.org/10.1063/1.1736196][DOI]]
- [[file:./resources/worlton1961.pdf][File]]


*** Citation
#+begin_src bibtex
@article{worlton1961,
  author =       {D. C. Worlton},
  title =        {Experimental Confirmation of Lamb Waves at Megacycle Frequencies},
  journal =      {J. Appl. Phys},
  year =         1961,
  volume =    32}
#+end_src

*** Summary
It gives a very gentle and simple introduction to the nature of Lamb waves.
It is not the original paper on Lamb waves (the one written by Lamb), but it one of the first ones to assess Lamb waves theoretically.
I have seen the original paper, and it has very heavy math, and because of that I was really impressed by the simplicity and depth of this paper.

* Other references

** The calculus of variations :calculus:of:variations:basic:literature:mechanics:
:PROPERTIES:
:ID: olver2021
:CATEGORY: Booklet
:END:
- Added: <2022-05-09 Mon>
- Year: 2021
- Author: Peter J. Olver

*** Resources
- [[https://www-users.cse.umn.edu/~olver/ln_/cv.pdf][Remote file]]
- [[file:./resources/olver2021.pdf][Local file]]

*** Citation
#+begin_src bibtex
@booklet{olver2021,
  title =        {The calculus of variations},
  author =    {Peter J. Olver},
  address =   {Minneapolis, MN},
  year =      2021}
#+end_src

*** Summary
A very gentle and basic introduction to Calculus of Variations.
I found that after reading this, I could understand very well the developments that appear in Lagrangian and Hamiltonian Mechanics.
It seems like it is actually aimed at engineers, because the Mathematics found in it is not heavy, and the content is presented in a form of tutorial, in a very simple and understandable way.

