#+TITLE: My personal library of scientific works
#+AUTHOR: Luis Paulo M. Lima
#+PROPERTY: header-args :tangle yes

* Introduction
This file contains entries for almost all of the papers I have
gathered for my research at CNU.  Each entry should be like this:

#+begin_src org :tangle no
  ,** Title
  This heading should contains a label with with the corresponding
  citation key for this entry, i.e., `<<luispauloml2020>>`, the
  year the work as published and the list of authors.

  ,*** Keywords
  The ``Keywords'' heading is empty and have tags that match the
  keywords given in the paper, if any. Personal tags may be added too.

  ,*** Summary
  A summary written by myself, sumarizing the contents of the paper.
  It should not be a copy of the abstract, by my own understanding of
  the what it contains.  It could also be simply a list with the main
  topics contained in it.  The links to this material shoube given
  after the summary, timestamps can be added after the links too, e.g.,
  ``Added: <YYYY-MM-DD>''.  At least one link should be given: to
  either a file or a internet reference where the paper can be found.
  If the reference is online, a DOI is prefered.

  ,*** Citation
  This heading contains the BibTeX entry for this work. For ease of
  use, the citation key is equal to the label of the `Title' heading.
  The code blocks can be tangle into a separate .bib file.
#+end_src

Each entry should also be placed under an appropriate top level
heading:
- Books and theses
- Conference papers
- Journal papers
- Others references

* Books and theses

** Two-dimensional signal and image processing <<jaeslim1990>>
- Year: 1990
- Author: Jae S. Lim

*** Keyworkds                                             :signal_processing:

*** TODO Summary
TBD.

Resources:
- [[file:./resources/jaeslim1990.djvu]]

Added: <2021-11-05 Fri>

*** Citation
#+begin_src bibtex
  @book{jaeslim1990,
      author = 	 {Jae S Lim},
      title = 	 {Two-dimensional signal and image processing},
      publisher =  {Prentice Hall},
      year = 	 1990,
      address = 	 {New Jersey}}
#+end_src

** Wave motion in elastic solids <<graff1975>>
- Year: 1975
- Author: Karl F. Graff

*** Keywordws                             :wave_propagation:basic_literature:

*** Summary
This was my entry point to the theory of wave propagation.  It
starts from 1D case for a string, then a rod, then beam, and give
exhaustive examples and explanations from every aspect and
question in each chapter.  It is an incredible resource for
learning but, at the same time, the math used here is very heavy.
However, by overlooking the hard points, it should help anyone
understand this topic.  I highly recommend it, and I also
recommend not to rush through it.  Take your time, it is not easy,
but it is very rewarding.

Resources:
- [[file:./resources/graff1975.pdf]]

Added: <2021-10-27 Wed>

*** Citation
#+begin_src bibtex
  @book{graff1975,
    author = 	 {Karl F. Graff},
    title = 	 {Wave motion in elastic solids},
    publisher = 	 {Dover Publications},
    year = 	 1975,
    address = 	 {New York}}
#+end_src

* Conference papers

** Exploring the performance limits of full-field acoustic wavenumber spectroscopy techniques for damage detection through numerical simulation <<odowd2016>>
- Year: 2016
- Authros:
  - Niall M. O'Dowd
  - Dae-Hyun Han
  - Lae-Hyong Kang
  - Eric B. Flynn

*** Keyworks                                                      :fem:aws:

*** TODO Summary
TBD.

Resources:
- [[https://www.ndt.net/search/docs.php3?id=20089][Conference website]]
- [[file:./resources/odowd2016.pdf]]

Added: <2021-11-22 Mon>

*** Citation
#+begin_src bibtex
  @inproceedings{odowd2016,
    author = 	 {Niall M. O'Dowd and Dae-Hyun Han and Lae-Hyong Kang and Eric B. Flynn},
    title = 	 {Exploring the performance limits of full-field acoustic wavenumber spectroscopy techniques for damage detection through numerical simulation},
    year = 	 2016,
    volume = 	 1,
    booktitle =    {8th European Workshop on Structural Health Monitoring}}
#+end_src

** Three-dimensional acoustic wavenumber spectroscopy for structural health monitoring <<fickenwirth2019>>
- Year: 2019
- Authors:
  - Peter H. Fickenwirth
  - Matthew J. Adams
  - Eric B. Flynn

*** Keywords                                                          :aws:

*** TODO Summary
TBD.

Resources:
- [[http://doi.org/10.12783/shm2019/32196][Conference website]]
- [[file:./resources/fickenwirth2019.pdf]]

Added: <2021-11-17 Wed>

*** Citation
#+begin_src bibtex
  @inproceedings{fickenwirth2019,
    author = 	 {Peter H. Fickenwirth and Matthew J. Adams and Eric B. Flynn},
    title = 	 {Three-dimensional acoustic wavenumber spectroscopy for structural health monitoring },
    booktitle = {12th International Workshop on Structural Health Monitoring},
    year = 	 2019,
    volume = 	 1}
#+end_src

** High-speed, non-contact, baseline-free imaging of hidden defects using scanning laser measurements of steady-state ultrasonic vibration <<flynn2013>>
- Year: 2013
- Authors:
  - E. B. Flynn
  - G. S. Jarmer

*** Keywords                                  :ldv:wavenumber:steady_state:

*** Summary
The most basic text for understanding LDV scanning.  It sets the
foundation for the techniques used at ASDL in a very simple way.
It lacks, however, a deeper explanation on how the /wavenumber
filter bank/ and the /monogenic signal/ work, and assumes that
this is common knowledge for anyone reading the paper (which, in
fact, should be).

Resources:
- [[https://www.dpi-proceedings.com/index.php/shm2013/article/view/22912][Conference website]]
- [[https://www.researchgate.net/publication/259102704_High-Speed_Non-Contact_Baseline-Free_Imaging_of_Hiddden_Defects_Using_Scanning_Laser_Measurements_of_Steady-State_Ultrasonic_Vibration][ResearchGate]]
- [[file:./resources/flynn2013.pdf]]

Added: <2021-10-21 Thu>

*** Citation
#+begin_src bibtex
  @inproceedings{flynn2013,
    author = 	 {E. B. Flynn and G. S. Jarmer},
    title = 	 {High-Speed, Non-Contact, Baseline-Free Imaging of
                    Hiddden Defects Using Scanning Laser Measurements of
                    Steady-State Ultrasonic Vibration},
    booktitle =	 {9th International Workshop on Structural Health
                    Monitoring},
    year =	 {2013},
    volume =	 {1}}
#+end_src

* Journal papers

** Structural imaging through local wavenumber estimation of guided waves <<flynn2013-2>>
- Year: 2013
- Authors:
  - Eric B. Flynn
  - See Yenn Chong
  - Gregory J. Jarmer
  - Jung-Ryul Lee

*** Keywords               :ndt:ldv:image_processing:ultrasonic:wavenumber:

*** TODO Summary
TBD.

Resources:
- [[https://doi.org/10.1016/j.ndteint.2013.04.003][Journal]]
- [[file:./resources/flynn2013-2.pdf]]

Added: <2021-11-23 Tue>

*** Citation
#+begin_src bibtex
  @article{flynn2013-2,
    title = {Structural imaging through local wavenumber estimation of guided waves},
    journal = {NDT \& E International},
    volume = {59},
    pages = {1-10},
    year = {2013},
    issn = {0963-8695},
    doi = {https://doi.org/10.1016/j.ndteint.2013.04.003},
    url = {https://www.sciencedirect.com/science/article/pii/S0963869513000595},
    author = {Eric B. Flynn and See Yenn Chong and Gregory J. Jarmer and Jung-Ryul Lee},
    keywords = {Nondestructive testing, Ultrasonic guided waves, Laser-generated ultrasound, Image processing}}
#+end_src

** Finite element prediction of wave motion in structural waveguides <<mace2005>>
- Year: 2005
- Authors:
  - Brian R. Mace
  - Denis Duhamel
  - Michael J. Brennan
  - Lars Hinke

*** Keywords                               :FEM:basic_literature:waveguide:

*** Summary
One of the most basic works on Finite Elements Method applied to
waveguides.  In contrast with other works, this one presents a simple
method that does not involve new types of elements, and depend only on
the regular stiffness, mass and damping matrices of the matrices used
in common FEM experiments.  Basic knowledge of FEM theory is the only
requirement to understand this paper.

Resources:
- [[https://doi.org/10.1121/1.1887126][Journal]]
- [[file:./resources/mace2005.pdf]]

Added: <2021-11-12 Fri>

*** Citation
#+begin_src bibtex
  @article{mace2005,
    author = {Brian R. Mace and Denis Duhamel and Michael J. Brennan and Lars Hinke},
    title = {Finite element prediction of wave motion in structural waveguides},
    journal = {The Journal of the Acoustical Society of America},
    volume = {117},
    number = {5},
    pages = {2835-2843},
    year = {2005},
    doi = {10.1121/1.1887126},
    URL = {https://doi.org/10.1121/1.1887126},
    eprint = {https://doi.org/10.1121/1.1887126}}
#+end_src

** Frequency-wavenumber domain filtering for improved damage visualization <<ruzzene2007>>
- Year:  2007
- Author: M Ruzzene

*** Keywords   :wavefield:wavenumber:filter:basic_literature:

*** Summary
Very short but very insightful paper presenting the concept of
filtering in the wavenumber-frequency domain. Although it leaves
out how to generate and how to apply the windows for filtering,
this paper should be considered basic literature for the work done
in ADSL.

Resources:
- [[https://doi.org/10.1063/1.2718150][Journal]]
- [[file:./resources/ruzzene2007.pdf]]

Added: <2021-10-27 Wed>
Updated: <2021-11-03 Wed>

*** Citation
#+begin_src bibtex
  @article{ruzzene2007,
    author = {M. Ruzzene},
    title = {Frequency‐Wavenumber Domain Filtering for Improved Damage Visualization},
    journal = {AIP Conference Proceedings},
    volume = {894},
    number = {1},
    pages = {1556-1563},
    year = {2007},
    doi = {10.1063/1.2718150},
    URL = {https://aip.scitation.org/doi/abs/10.1063/1.2718150},
    eprint = {https://aip.scitation.org/doi/pdf/10.1063/1.2718150}}
#+end_src

** 2D-wavelet wavenumber filtering for structural damage detection using full steady-state wavefield laser scanning <<junyoung2020>>
- Year: 2020
- Authors:
  - Jun Young Jeon
  - Duhwan Kim
  - Gyuhae Park
  - Eric Flynn
  - To Kang
  - Soonwoo Han

*** Keywords :steady_state_wavefield:shm:nondestructive_evaluation:damage_detection:wavelet:laser:ldv:

*** TODO Summary
TBD.

Resources:
- [[https://doi.org/10.1016/j.ndteint.2020.102343][Journal]]
- [[file:./resources/junyoung2020.pdf]]

Added: <2021-10-22 Fri>

*** Citation
#+begin_src bibtex
  @article{junyoung2020,
    title = {2D-wavelet wavenumber filtering for structural damage detection using full steady-state wavefield laser scanning},
    journal = {NDT & E International},
    volume = {116},
    pages = {102343},
    year = {2020},
    issn = {0963-8695},
    doi = {https://doi.org/10.1016/j.ndteint.2020.102343},
    url = {https://www.sciencedirect.com/science/article/pii/S0963869520300384},
    author = {Jun Young Jeon and Duhwan Kim and Gyuhae Park and Eric Flynn and To Kang and Soonwoo Han},
    keywords = {Steady-state wavefield, Structural health monitoring, Nondestructive evaluation, Damage detection, 2D-wavelet filter, Laser scanning}}
#+end_src

* Other references
  Empty.
